### ISSUE TITLE
(data) Add C++ binding for thumbnail generation

### ISSUE THREAD

**Issue by kylinmb** [SCIInstitute/dSpaceX#184]
The PCA models for meshs and volumes generate new meshes and volumes. In order to display the predictions in the UI thumbnails will need to be generated. Currently, there are methods in the python data processing pipeline to generate thumbnails, but there is no way to call these functions from C++. If we create binding the C++ will be able to call these functions.

**Comment by cchriste** [comment]
specific use cases for this issue are nanoparticles_mesh and nanoparticles_volume

**Comment by cchriste** [comment]
done
