### ISSUE TITLE
Improve Lighting in Morse-Smale Decomposition Window OR Make it obvious which crystal is selected

### ISSUE THREAD

**Issue by kylinmb** [SCIInstitute/dSpaceX#19]
Make lighting more uniform. Still want object to appear 3D however there are dark spots and weird artifacts because the lighting isn't quite right.

**Comment by kylinmb** [comment]
It is kind of hard to tell which crystal is currently selected, especially if you take your focus away from the window. I need to improve the view so that this is very clear!

**Comment by cchriste** [comment]
Improved crystal navigation and selection has been achieved with better light source placement, perspective camera, and glowing halo around selected crystal.
