### ISSUE TITLE
Embedding and Morse-Smale Canvas height continue to grow when shrinking browser window

### ISSUE THREAD

**Issue by kylinmb** [SCIInstitute/dSpaceX#99]
I logged this issue so I have somewhere to save the below url for the fix.

https://stackoverflow.com/questions/41814539/html-div-height-keeps-growing-on-window-resize-event

**Comment by kylinmb** [comment]
This was slightly improved by using line mentioned in link above. However, another outstanding issue is when widening the screen the height increases too, I don't think that should be the case.

**Comment by cchriste** [comment]
fixed
